name: Security Dependency Checker
description: Check for any security issues in dependencies

runs:
  using: "composite"
  steps:
    - id: security_checker_run
      run: ${{ github.action_path }}/security.sh || { cat ${{ github.workspace }}/output.log ; exit 1; }
      shell: bash

branding:
  icon: 'check-square'
  color: 'purple'