name: Tests
description: Run tests with phpunit

runs:
  using: "composite"
  steps:
    - id: phpunit_run
      run: ${{ github.action_path }}/phpunit.sh || { cat ${{ github.workspace }}/output.log ; exit 1; }
      shell: bash

branding:
  icon: 'check-square'
  color: 'purple'