name: PHP Cs Fixer Check
description: Code style check with php-cs-fixer

runs:
  using: "composite"
  steps:
    - id: php_cs_run
      run: ${{ github.action_path }}/phpcs_fixer.sh || { cat ${{ github.workspace }}/output.log ; exit 1; }
      shell: bash

branding:
  icon: 'check-square'
  color: 'purple'